@startuml VideoGameStore
skinparam defaultFontName "JetBrains Mono"

enum Category {
    ACTION
    PUZZLE
    SIMULATION
}

class Game {
    - {static} totalRevenue: float
    - title: String
    - genre: Category
    - ageRating: int
    - popularityScore: float
    - damagedStatus: bool
    - rentalRate: float
    - totalRentsCount: int
    - isAvailable: bool
    ---
    + Game(title: String, genre: Category, ageRating: int, popularityScore: float,
    rentalRate: float, totalRentsCount: int, isAvailable: bool)
    + {static} findMostPopular(List<Game>): Game
    + {static} browseGenre(List<Game>, Category): List<Game>
    + {static} browseAge(List<Game>, int): List<Game>
    + rent(hours): bool
    + return(promisedHours, realHours): float
    + {static} getTotalRevenue(): float
}

note right of Game::findMostPopular
    print("The most popular game right now is ")
    return max(List<Game>.popularity_score)
end note

note right of Game::Game
    damagedStatus = totalRentsCount > 20
    isAvailable = isAvailable && !damagedStatus
end note

note right of Game::browseGenre
    print("Here are all the games in " + Category + " sorted by their popularity:")
    return games where genre == Category, sorted by popularityScore desc
end note

note right of Game::browseAge
    print("At your age of " + int + ", the following games are the most popular:")
    return games where ageRating <= age, sorted by popularityScore desc
end note

note right of Game::rent
    if damagedStatus:
        print("Can't do it, the game is damaged :(")
        return false
    if !isAvailable:
        print("Can't do it, the game is not available right now.")
        return false
    else:
        print("Here is your game!")
        totalRentsCount++
        damagedStatus = totalRentsCount > 20
        isAvailable = false
        return true
end note

note right of Game::return
    if realHours > promisedHours:
        print("You're late! Here's your total:")
        return (promisedHours + (realHours - promisedHours) * 2) * rental_rate
    else:
        print("Alright! Here is your total:")
        return realHours * rental_rate
    totalRevenue += total
    if !damagedStatus:
        isAvailable = true

end note

note right of Game::getTotalRevenue
    return totalRevenue
end note

Game +-- Category
@enduml