<?php
$nations = [
  "ALB" => ["id" => "ALB", "name" => "Albania", "flag" => "🇦🇱", "points" => 0],
  "AND" => ["id" => "AND", "name" => "Andorra", "flag" => "🇦🇩", "points" => 0],
  "ARM" => ["id" => "ARM", "name" => "Armenia", "flag" => "🇦🇲", "points" => 0],
  "AUS" => ["id" => "AUS", "name" => "Australia", "flag" => "🇦🇺", "points" => 0],
  "AUT" => ["id" => "AUT", "name" => "Austria", "flag" => "🇦🇹", "points" => 0],
  "AZE" => ["id" => "AZE", "name" => "Azerbaijan", "flag" => "🇦🇿", "points" => 0],
  "BEL" => ["id" => "BEL", "name" => "Belgium", "flag" => "🇧🇪", "points" => 0],
  "BIH" => ["id" => "BIH", "name" => "Bosnia and Herzegovina", "flag" => "🇧🇦", "points" => 0],
  "BGR" => ["id" => "BGR", "name" => "Bulgaria", "flag" => "🇧🇬", "points" => 0],
  "HRV" => ["id" => "HRV", "name" => "Croatia", "flag" => "🇭🇷", "points" => 0],
  "CYP" => ["id" => "CYP", "name" => "Cyprus", "flag" => "🇨🇾", "points" => 0],
  "CZE" => ["id" => "CZE", "name" => "Czech Republic", "flag" => "🇨🇿", "points" => 0],
  "DNK" => ["id" => "DNK", "name" => "Denmark", "flag" => "🇩🇰", "points" => 0],
  "EST" => ["id" => "EST", "name" => "Estonia", "flag" => "🇪🇪", "points" => 0],
  "FIN" => ["id" => "FIN", "name" => "Finland", "flag" => "🇫🇮", "points" => 0],
  "FRA" => ["id" => "FRA", "name" => "France", "flag" => "🇫🇷", "points" => 0],
  "GEO" => ["id" => "GEO", "name" => "Georgia", "flag" => "🇬🇪", "points" => 0],
  "DEU" => ["id" => "DEU", "name" => "Germany", "flag" => "🇩🇪", "points" => 0],
  "GRC" => ["id" => "GRC", "name" => "Greece", "flag" => "🇬🇷", "points" => 0],
  "HUN" => ["id" => "HUN", "name" => "Hungary", "flag" => "🇭🇺", "points" => 0],
  "ISL" => ["id" => "ISL", "name" => "Iceland", "flag" => "🇮🇸", "points" => 0],
  "IRL" => ["id" => "IRL", "name" => "Ireland", "flag" => "🇮🇪", "points" => 0],
  "ISR" => ["id" => "ISR", "name" => "Israel", "flag" => "🇮🇱", "points" => 0],
  "ITA" => ["id" => "ITA", "name" => "Italy", "flag" => "🇮🇹", "points" => 0],
  "KAZ" => ["id" => "KAZ", "name" => "Kazakhstan", "flag" => "🇰🇿", "points" => 0],
  "LVA" => ["id" => "LVA", "name" => "Latvia", "flag" => "🇱🇻", "points" => 0],
  "LTU" => ["id" => "LTU", "name" => "Lithuania", "flag" => "🇱🇹", "points" => 0],
  "LUX" => ["id" => "LUX", "name" => "Luxembourg", "flag" => "🇱🇺", "points" => 0],
  "MLT" => ["id" => "MLT", "name" => "Malta", "flag" => "🇲🇹", "points" => 0],
  "MDA" => ["id" => "MDA", "name" => "Moldova", "flag" => "🇲🇩", "points" => 0],
  "MCO" => ["id" => "MCO", "name" => "Monaco", "flag" => "🇲🇨", "points" => 0],
  "MNE" => ["id" => "MNE", "name" => "Montenegro", "flag" => "🇲🇪", "points" => 0],
  "NLD" => ["id" => "NLD", "name" => "Netherlands", "flag" => "🇳🇱", "points" => 0],
  "MKD" => ["id" => "MKD", "name" => "Macedonia", "flag" => "🇲🇰", "points" => 0],
  "NOR" => ["id" => "NOR", "name" => "Norway", "flag" => "🇳🇴", "points" => 0],
  "POL" => ["id" => "POL", "name" => "Poland", "flag" => "🇵🇱", "points" => 0],
  "PRT" => ["id" => "PRT", "name" => "Portugal", "flag" => "🇵🇹", "points" => 0],
  "ROU" => ["id" => "ROU", "name" => "Romania", "flag" => "🇷🇴", "points" => 0],
  "SMR" => ["id" => "SMR", "name" => "San Marino", "flag" => "🇸🇲", "points" => 0],
  "SRB" => ["id" => "SRB", "name" => "Serbia", "flag" => "🇷🇸", "points" => 0],
  "SVK" => ["id" => "SVK", "name" => "Slovakia", "flag" => "🇸🇰", "points" => 0],
  "SVN" => ["id" => "SVN", "name" => "Slovenia", "flag" => "🇸🇮", "points" => 0],
  "ESP" => ["id" => "ESP", "name" => "Spain", "flag" => "🇪🇸", "points" => 0],
  "SWE" => ["id" => "SWE", "name" => "Sweden", "flag" => "🇸🇪", "points" => 0],
  "CHE" => ["id" => "CHE", "name" => "Switzerland", "flag" => "🇨🇭", "points" => 0],
  "TUR" => ["id" => "TUR", "name" => "Turkey", "flag" => "🇹🇷", "points" => 0],
  "UKR" => ["id" => "UKR", "name" => "Ukraine", "flag" => "🇺🇦", "points" => 0],
  "GBR" => ["id" => "GBR", "name" => "United Kingdom", "flag" => "🇬🇧", "points" => 0]
];
