const taskA = document.querySelector('#taskA')
const taskB = document.querySelector('#taskB')
const taskC = document.querySelector('#taskC')
const taskE = document.querySelector('#taskD')
const taskF = document.querySelector('#taskE')