const nations = {
    ALB: `Albania`,
    AND: `Andorra`,
    ARM: `Armenia`,
    AUS: `Australia`,
    AUT: `Austria`,
    AZE: `Azerbaijan`,
    BEL: `Belgium`,
    BIH: `Bosnia and Herzegovina`,
    BGR: `Bulgaria`,
    HRV: `Croatia`,
    CYP: `Cyprus`,
    CZE: `Czechia`,
    DNK: `Denmark`,
    EST: `Estonia`,
    FIN: `Finland`,
    FRA: `France`,
    GEO: `Georgia`,
    DEU: `Germany`,
    GRC: `Greece`,
    HUN: `Hungary`,
    ISL: `Iceland`,
    IRL: `Ireland`,
    ISR: `Israel`,
    ITA: `Italy`,
    KAZ: `Kazakhstan`,
    LVA: `Latvia`,
    LTU: `Lithuania`,
    LUX: `Luxembourg`,
    MLT: `Malta`,
    MDA: `Moldova`,
    MCO: `Monaco`,
    MNE: `Montenegro`,
    NLD: `Netherlands`,
    MKD: `Macedonia`,
    NOR: `Norway`,
    POL: `Poland`,
    PRT: `Portugal`,
    ROU: `Romania`,
    SMR: `San Marino`,
    SRB: `Serbia`,
    SVK: `Slovakia`,
    SVN: `Slovenia`,
    ESP: `Spain`,
    SWE: `Sweden`,
    CHE: `Switzerland`,
    TUR: `Turkey`,
    UKR: `Ukraine`,
    GBR: `United Kingdom`
}