const participants = [
    { nation: 'AUS', type: 'singer', name: 'Delta Goodrem' },
    { nation: 'AUS', type: 'band', name: 'Tame Impala' },
    { nation: 'AUS', type: 'band', name: 'Gang of Youths' },
    { nation: 'AUT', type: 'singer', name: 'Conchita Wurst' },
    { nation: 'AUT', type: 'band', name: 'Wanda' },
    { nation: 'AUT', type: 'singer', name: 'Christina Stürmer' },
    { nation: 'AUT', type: 'band', name: 'Bilderbuch' },
    { nation: 'AUT', type: 'band', name: 'Klangkarussell' },
    { nation: 'CHE', type: 'singer', name: 'Nemo' },
    { nation: 'CHE', type: 'band', name: 'Swiss Grd.' },
    { nation: 'CZE', type: 'singer', name: 'Ewa Farna' },
    { nation: 'CZE', type: 'singer', name: 'Mikolas Josef' },
    { nation: 'HRV', type: 'band', name: 'Baby Lasagna' },
    { nation: 'FRA', type: 'singer', name: 'Christine Valerie' },
    { nation: 'FRA', type: 'singer', name: 'Stromae' },
    { nation: 'FRA', type: 'singer', name: 'Zaz' },
    { nation: 'FRA', type: 'singer', name: 'Indila de Bourbone' },
    { nation: 'FRA', type: 'singer', name: 'Vianney' },
    { nation: 'FRA', type: 'singer', name: 'M. Pokora' },
    { nation: 'GBR', type: 'singer', name: 'Adele' },
    { nation: 'GBR', type: 'band', name: 'Coldplay' },
    { nation: 'GBR', type: 'singer', name: 'Ed Sheeran' },
    { nation: 'GBR', type: 'band', name: 'Arctic Monkeys' },
    { nation: 'GBR', type: 'singer', name: 'Dua Lipa' },
    { nation: 'GBR', type: 'band', name: 'Radiohead' },
    { nation: 'GBR', type: 'band', name: 'Bitlis' },
    { nation: 'HUN', type: 'singer', name: 'Oláh Ibolya' },
    { nation: 'HUN', type: 'band', name: 'Carson Coma' },
    { nation: 'HUN', type: 'band', name: 'Alvin és a Mókusok' },
    { nation: 'NLD', type: 'band', name: 'Within Temptation' },
    { nation: 'NLD', type: 'singer', name: 'Anouk' },
    { nation: 'NLD', type: 'band', name: 'Kensington' },
    { nation: 'NLD', type: 'singer', name: 'Davina Michelle' },
    { nation: 'NLD', type: 'band', name: 'Go Back To The Zoo' },
    { nation: 'POL', type: 'singer', name: 'Dawid Podsiadło' },
    { nation: 'POL', type: 'band', name: 'Riverside' },
    { nation: 'POL', type: 'singer', name: 'Margaret' },
    { nation: 'POL', type: 'band', name: 'Behemoth' },
]