<?php
$nations = [
  "ALB" => ["id" => "ALB", "name" => "Albania", "flag" => "🇦🇱"],
  "AND" => ["id" => "AND", "name" => "Andorra", "flag" => "🇦🇩"],
  "ARM" => ["id" => "ARM", "name" => "Armenia", "flag" => "🇦🇲"],
  "AUS" => ["id" => "AUS", "name" => "Australia", "flag" => "🇦🇺"],
  "AUT" => ["id" => "AUT", "name" => "Austria", "flag" => "🇦🇹"],
  "AZE" => ["id" => "AZE", "name" => "Azerbaijan", "flag" => "🇦🇿"],
  "BEL" => ["id" => "BEL", "name" => "Belgium", "flag" => "🇧🇪"],
  "BIH" => ["id" => "BIH", "name" => "Bosnia and Herzegovina", "flag" => "🇧🇦"],
  "BGR" => ["id" => "BGR", "name" => "Bulgaria", "flag" => "🇧🇬"],
  "HRV" => ["id" => "HRV", "name" => "Croatia", "flag" => "🇭🇷"],
  "CYP" => ["id" => "CYP", "name" => "Cyprus", "flag" => "🇨🇾"],
  "CZE" => ["id" => "CZE", "name" => "Czech Republic", "flag" => "🇨🇿"],
  "DNK" => ["id" => "DNK", "name" => "Denmark", "flag" => "🇩🇰"],
  "EST" => ["id" => "EST", "name" => "Estonia", "flag" => "🇪🇪"],
  "FIN" => ["id" => "FIN", "name" => "Finland", "flag" => "🇫🇮"],
  "FRA" => ["id" => "FRA", "name" => "France", "flag" => "🇫🇷"],
  "GEO" => ["id" => "GEO", "name" => "Georgia", "flag" => "🇬🇪"],
  "DEU" => ["id" => "DEU", "name" => "Germany", "flag" => "🇩🇪"],
  "GRC" => ["id" => "GRC", "name" => "Greece", "flag" => "🇬🇷"],
  "HUN" => ["id" => "HUN", "name" => "Hungary", "flag" => "🇭🇺"],
  "ISL" => ["id" => "ISL", "name" => "Iceland", "flag" => "🇮🇸"],
  "IRL" => ["id" => "IRL", "name" => "Ireland", "flag" => "🇮🇪"],
  "ISR" => ["id" => "ISR", "name" => "Israel", "flag" => "🇮🇱"],
  "ITA" => ["id" => "ITA", "name" => "Italy", "flag" => "🇮🇹"],
  "KAZ" => ["id" => "KAZ", "name" => "Kazakhstan", "flag" => "🇰🇿"],
  "LVA" => ["id" => "LVA", "name" => "Latvia", "flag" => "🇱🇻"],
  "LTU" => ["id" => "LTU", "name" => "Lithuania", "flag" => "🇱🇹"],
  "LUX" => ["id" => "LUX", "name" => "Luxembourg", "flag" => "🇱🇺"],
  "MLT" => ["id" => "MLT", "name" => "Malta", "flag" => "🇲🇹"],
  "MDA" => ["id" => "MDA", "name" => "Moldova", "flag" => "🇲🇩"],
  "MCO" => ["id" => "MCO", "name" => "Monaco", "flag" => "🇲🇨"],
  "MNE" => ["id" => "MNE", "name" => "Montenegro", "flag" => "🇲🇪"],
  "NLD" => ["id" => "NLD", "name" => "Netherlands", "flag" => "🇳🇱"],
  "MKD" => ["id" => "MKD", "name" => "Macedonia", "flag" => "🇲🇰"],
  "NOR" => ["id" => "NOR", "name" => "Norway", "flag" => "🇳🇴"],
  "POL" => ["id" => "POL", "name" => "Poland", "flag" => "🇵🇱"],
  "PRT" => ["id" => "PRT", "name" => "Portugal", "flag" => "🇵🇹"],
  "ROU" => ["id" => "ROU", "name" => "Romania", "flag" => "🇷🇴"],
  "SMR" => ["id" => "SMR", "name" => "San Marino", "flag" => "🇸🇲"],
  "SRB" => ["id" => "SRB", "name" => "Serbia", "flag" => "🇷🇸"],
  "SVK" => ["id" => "SVK", "name" => "Slovakia", "flag" => "🇸🇰"],
  "SVN" => ["id" => "SVN", "name" => "Slovenia", "flag" => "🇸🇮"],
  "ESP" => ["id" => "ESP", "name" => "Spain", "flag" => "🇪🇸"],
  "SWE" => ["id" => "SWE", "name" => "Sweden", "flag" => "🇸🇪"],
  "CHE" => ["id" => "CHE", "name" => "Switzerland", "flag" => "🇨🇭"],
  "TUR" => ["id" => "TUR", "name" => "Turkey", "flag" => "🇹🇷"],
  "UKR" => ["id" => "UKR", "name" => "Ukraine", "flag" => "🇺🇦"],
  "GBR" => ["id" => "GBR", "name" => "United Kingdom", "flag" => "🇬🇧"]
];
