<?php
$nations = [
  "Albania", 
  "Andorra", 
  "Armenia", 
  "Australia", 
  "Austria", 
  "Azerbaijan", 
  "Belgium", 
  "Bosnia and Herzegovina", 
  "Bulgaria", 
  "Croatia", 
  "Cyprus", 
  "Czech Republic", 
  "Denmark", 
  "Estonia", 
  "Finland", 
  "France", 
  "Georgia", 
  "Germany", 
  "Greece", 
  "Hungary", 
  "Iceland", 
  "Ireland", 
  "Israel", 
  "Italy", 
  "Kazakhstan", 
  "Latvia", 
  "Lithuania", 
  "Luxembourg", 
  "Malta", 
  "Moldova", 
  "Monaco", 
  "Montenegro", 
  "Netherlands", 
  "Macedonia", 
  "Norway", 
  "Poland", 
  "Portugal", 
  "Romania", 
  "San Marino", 
  "Serbia", 
  "Slovakia", 
  "Slovenia", 
  "Spain", 
  "Sweden", 
  "Switzerland", 
  "Turkey", 
  "Ukraine", 
  "United Kingdom"
];
