<?php
$videos = [
    (object)[ "id" => "0573ddf4", "title" => "Alexander Rybak - Fairytale", "nation" => "" ],
    (object)[ "id" => "069687d6", "title" => "Loreen - Euphoria", "nation" => "" ],
    (object)[ "id" => "1479a2fe", "title" => "JJ - Wasted Love", "nation" => "" ],
    (object)[ "id" => "31fb4561", "title" => "AWS - Viszlát Nyár", "nation" => "" ],
    (object)[ "id" => "3591afee", "title" => "Slimane - Mon Amour", "nation" => "" ],
    (object)[ "id" => "3d8d0e8d", "title" => "Loreen - Tattoo", "nation" => "" ],
    (object)[ "id" => "42232d21", "title" => "Olsen Brothers - Fly On The Wings of Love", "nation" => "" ],
    (object)[ "id" => "4cc18091", "title" => "Miriana Conte - SERVING", "nation" => "" ],
    (object)[ "id" => "56c12e67", "title" => "Måneskin - Zitti E Buoni", "nation" => "" ],
    (object)[ "id" => "5f96af67", "title" => "Chanel - SloMo", "nation" => "" ],
    (object)[ "id" => "61b3731a", "title" => "Conchita Wurst - Rise Like a Phoenix", "nation" => "" ],
    (object)[ "id" => "62860074", "title" => "Tommy Cash - Espresso Macchiato", "nation" => "" ],
    (object)[ "id" => "685f4943", "title" => "Dino Merlin - Love In Rewind", "nation" => "" ],
    (object)[ "id" => "6b447408", "title" => "Joost Klein - Europapa", "nation" => "" ],
    (object)[ "id" => "6fb178a2", "title" => "Little Big - Uno", "nation" => "" ],
    (object)[ "id" => "70621e6b", "title" => "Basim - Cliché Love Song", "nation" => "" ],
    (object)[ "id" => "74cfa0d1", "title" => "ABBA - Waterloo", "nation" => "" ],
    (object)[ "id" => "846882bd", "title" => "Nebulossa - ZORRA", "nation" => "" ],
    (object)[ "id" => "9350ed07", "title" => "Måns Zelmerlöw - Heroes", "nation" => "" ],
    (object)[ "id" => "938a4a4d", "title" => "Bambie Thug - Doomsday Blue", "nation" => "" ],
    (object)[ "id" => "9921812f", "title" => "Windows95man - No Rules!", "nation" => "" ],
    (object)[ "id" => "a2901c3f", "title" => "Sunstroke Project & Olia Tira - Run Away", "nation" => "" ],
    (object)[ "id" => "a9db35a0", "title" => "Verka Serduchka - Dancing Lasha Tumbai", "nation" => "" ],
    (object)[ "id" => "b0c6c269", "title" => "Subwoolfer - Give That Wolf A Banana", "nation" => "" ],
    (object)[ "id" => "c10cd2e8", "title" => "Baby Lasagna - Rim Tim Tagi Dim", "nation" => "" ],
    (object)[ "id" => "c74d1bcd", "title" => "Netta - Toy", "nation" => "" ],
    (object)[ "id" => "d2fa5d22", "title" => "Käärijä - Cha Cha Cha", "nation" => "" ],
    (object)[ "id" => "d7e6f881", "title" => "Joci Pápai - Origo", "nation" => "" ],
    (object)[ "id" => "e0701ae3", "title" => "Lordi - Hard Rock Hallelujah", "nation" => "" ],
    (object)[ "id" => "e0c8b1b9", "title" => "Ivi Adamou - La La Love", "nation" => "" ],
    (object)[ "id" => "f6b33937", "title" => "Nemo - The Code", "nation" => "" ],
    (object)[ "id" => "fddc8c5d", "title" => "EMMY - Laika Party", "nation" => "" ]
];
?>